import type { Event } from '@ttg/types'

// Today: 2026-06-19
// evt-001  completed  Dragon's Lair Praha    MTG Sealed       Jun 14
// evt-002  active     Dragon's Lair Praha    MTG 2HG          Jun 16
// evt-003  upcoming   Dragon's Lair Praha    MTG Sealed       Jun 28  18/28
// evt-004  upcoming   Dragon's Lair Praha    MTG 2HG          Jun 28   6/16
// evt-005  upcoming   Mythic Games  Brno     MTG Sealed FULL  Jun 28  24/24 + 8 waitlist
// evt-006  upcoming   Mana Vault    Brno     MTG 2HG   FULL  Jun 28  16/16 + 4 waitlist
// evt-007  upcoming   Mythic Games  Brno     Lorcana Sealed   Jul  5  12/20
// evt-008  upcoming   Mana Vault    Brno     Pokémon Standard Jul  5  15/32
// evt-009  upcoming   Shield&Sword  Plzeň    MTG Draft        Jul 12   8/24
// evt-010  completed  Critical Hit  Bratislava  Pokémon Reg.  May 30
// evt-011  completed  Card Kingdom  Ostrava  Yu-Gi-Oh Tourney Jun  7
// evt-012  upcoming   Dragon's Lair Praha    MTG Prerelease   Jul 19  12/24

export const EVENTS: Event[] = [
  {
    id: 'evt-001',
    storeId: 'str-001',
    name: 'Aetherdrift Prerelease — Sealed',
    game: 'mtg',
    format: 'sealed',
    type: 'prerelease',
    status: 'completed',
    date: '2026-06-14',
    time: '10:00',
    capacity: 28,
    waitlistCapacity: 10,
    entryFee: 280,
    currency: 'CZK',
    notes: 'Bring your Companion app name. Pairings posted at the store. Pay 280 CZK at the door.',
    companionApp: true,
    createdAt: '2026-05-20T08:00:00Z',
  },
  {
    id: 'evt-002',
    storeId: 'str-001',
    name: 'Aetherdrift Prerelease — 2HG',
    game: 'mtg',
    format: '2hg',
    type: 'prerelease',
    status: 'active',
    date: '2026-06-16',
    time: '14:00',
    capacity: 16,
    waitlistCapacity: 8,
    entryFee: 320,
    currency: 'CZK',
    notes: 'Two-Headed Giant format. Register as a team or solo — we will pair you.',
    companionApp: false,
    createdAt: '2026-05-20T08:00:00Z',
  },
  {
    id: 'evt-003',
    storeId: 'str-001',
    name: 'Aetherdrift Launch Event — Sealed',
    game: 'mtg',
    format: 'sealed',
    type: 'launch',
    status: 'upcoming',
    date: '2026-06-28',
    time: '10:00',
    capacity: 28,
    waitlistCapacity: 10,
    entryFee: 300,
    currency: 'CZK',
    notes: 'Celebrate the official release of Aetherdrift. 6 packs + promo card.',
    companionApp: true,
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'evt-004',
    storeId: 'str-001',
    name: 'Aetherdrift Launch Event — 2HG',
    game: 'mtg',
    format: '2hg',
    type: 'launch',
    status: 'upcoming',
    date: '2026-06-28',
    time: '14:00',
    capacity: 16,
    waitlistCapacity: 8,
    entryFee: 340,
    currency: 'CZK',
    notes: 'Team of 2. Register together or let us find you a partner.',
    companionApp: false,
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'evt-005',
    storeId: 'str-002',
    name: 'Aetherdrift Prerelease — Sealed',
    game: 'mtg',
    format: 'sealed',
    type: 'prerelease',
    status: 'upcoming',
    date: '2026-06-28',
    time: '11:00',
    capacity: 24,
    waitlistCapacity: 10,
    entryFee: 290,
    currency: 'CZK',
    notes: 'Event is FULL — waitlist open. We will notify you if a spot opens.',
    companionApp: true,
    createdAt: '2026-05-22T08:00:00Z',
  },
  {
    id: 'evt-006',
    storeId: 'str-003',
    name: 'Aetherdrift Prerelease — 2HG',
    game: 'mtg',
    format: '2hg',
    type: 'prerelease',
    status: 'upcoming',
    date: '2026-06-28',
    time: '13:00',
    capacity: 16,
    waitlistCapacity: 8,
    entryFee: 330,
    currency: 'CZK',
    notes: 'FULL — waitlist only. Teams of 2.',
    companionApp: false,
    createdAt: '2026-05-25T08:00:00Z',
  },
  {
    id: 'evt-007',
    storeId: 'str-002',
    name: 'Lorcana Into the Inklands — Sealed',
    game: 'lorcana',
    format: 'sealed',
    type: 'regular',
    status: 'upcoming',
    date: '2026-07-05',
    time: '13:00',
    capacity: 20,
    waitlistCapacity: 6,
    entryFee: 350,
    currency: 'CZK',
    notes: 'Build your 40-card Lorcana deck from 6 sealed booster packs.',
    companionApp: false,
    createdAt: '2026-06-05T08:00:00Z',
  },
  {
    id: 'evt-008',
    storeId: 'str-003',
    name: 'Pokémon Standard Tournament',
    game: 'pokemon',
    format: 'standard',
    type: 'regular',
    status: 'upcoming',
    date: '2026-07-05',
    time: '11:00',
    capacity: 32,
    waitlistCapacity: 8,
    entryFee: 150,
    currency: 'CZK',
    notes: 'Standard format. Bring a legal 60-card deck. Best of 3 per round.',
    companionApp: false,
    createdAt: '2026-06-06T09:00:00Z',
  },
  {
    id: 'evt-009',
    storeId: 'str-006',
    name: 'Aetherdrift Draft Night',
    game: 'mtg',
    format: 'draft',
    type: 'regular',
    status: 'upcoming',
    date: '2026-07-12',
    time: '14:00',
    capacity: 24,
    waitlistCapacity: 8,
    entryFee: 250,
    currency: 'CZK',
    notes: 'Swiss draft. 3 packs of Aetherdrift. 3 rounds of Swiss.',
    companionApp: false,
    createdAt: '2026-06-08T10:00:00Z',
  },
  {
    id: 'evt-010',
    storeId: 'str-004',
    name: 'Pokémon Regional — Standard',
    game: 'pokemon',
    format: 'standard',
    type: 'championship',
    status: 'completed',
    date: '2026-05-30',
    time: '10:00',
    capacity: 32,
    waitlistCapacity: 0,
    entryFee: 200,
    currency: 'EUR',
    notes: 'Regional championship. Top 8 prize support.',
    companionApp: false,
    createdAt: '2026-04-15T08:00:00Z',
  },
  {
    id: 'evt-011',
    storeId: 'str-005',
    name: 'Yu-Gi-Oh! Local Tournament',
    game: 'yugioh',
    format: 'standard',
    type: 'regular',
    status: 'completed',
    date: '2026-06-07',
    time: '13:00',
    capacity: 20,
    waitlistCapacity: 0,
    entryFee: 80,
    currency: 'CZK',
    notes: 'Advanced format. Bring your Main/Extra/Side decks.',
    companionApp: false,
    createdAt: '2026-05-10T08:00:00Z',
  },
  {
    id: 'evt-012',
    storeId: 'str-001',
    name: 'Tarkir: Dragonstorm Prerelease — Sealed',
    game: 'mtg',
    format: 'sealed',
    type: 'prerelease',
    status: 'upcoming',
    date: '2026-07-19',
    time: '10:00',
    capacity: 24,
    waitlistCapacity: 8,
    entryFee: 300,
    currency: 'CZK',
    notes: 'Prerelease sealed event for Tarkir: Dragonstorm. 6 packs + promo card. Pairings on Companion app.',
    companionApp: true,
    createdAt: '2026-06-19T09:00:00Z',
  },
]
