import type { Store, StoreApplication } from '@ttg/types'

// ─── 6 active stores ─────────────────────────────────────────────────────────
// Note: str-002 (Mythic Games) and str-003 (Mana Vault) are both in Brno.
// City filter for "Brno" returns events from both stores.

export const STORES: Store[] = [
  {
    id: 'str-001',
    slug: 'dragons-lair',
    name: "Dragon's Lair",
    city: 'Praha',
    country: 'CZ',
    address: 'Náměstí Míru 12, Praha 2',
    website: 'https://dragonslair.cz',
    tier: 'pro',
    status: 'active',
    adminIds: ['usr-002'],
    createdAt: '2025-08-01T08:00:00Z',
  },
  {
    id: 'str-002',
    slug: 'mythic-games',
    name: 'Mythic Games',
    city: 'Brno',
    country: 'CZ',
    address: 'Česká 14, Brno-střed',
    website: 'https://mythicgames.cz',
    tier: 'pro',
    status: 'active',
    adminIds: ['usr-020'],
    createdAt: '2025-09-15T09:00:00Z',
  },
  {
    id: 'str-003',
    slug: 'mana-vault',
    name: 'Mana Vault',
    city: 'Brno',
    country: 'CZ',
    address: 'Husova 8, Brno-střed',
    website: 'https://manavault.cz',
    tier: 'basic',
    status: 'active',
    adminIds: ['usr-030'],
    createdAt: '2025-11-20T10:00:00Z',
  },
  {
    id: 'str-004',
    slug: 'critical-hit',
    name: 'Critical Hit',
    city: 'Bratislava',
    country: 'SK',
    address: 'Obchodná 28, Bratislava I',
    website: 'https://criticalhit.sk',
    tier: 'free',
    status: 'active',
    adminIds: ['usr-034'],
    createdAt: '2025-10-05T08:00:00Z',
  },
  {
    id: 'str-005',
    slug: 'card-kingdom',
    name: 'Card Kingdom',
    city: 'Ostrava',
    country: 'CZ',
    address: 'Stodolní 5, Moravská Ostrava',
    tier: 'free',
    status: 'active',
    adminIds: ['usr-040'],
    createdAt: '2025-12-01T08:00:00Z',
  },
  {
    id: 'str-006',
    slug: 'shield-and-sword',
    name: 'Shield & Sword',
    city: 'Plzeň',
    country: 'CZ',
    address: 'Klatovská 12, Plzeň 1',
    website: 'https://shieldsword.cz',
    tier: 'basic',
    status: 'active',
    adminIds: ['usr-048'],
    createdAt: '2026-01-10T09:00:00Z',
  },
]

// ─── 3 pending store applications ───────────────────────────────────────────

export const STORE_APPLICATIONS: StoreApplication[] = [
  {
    id: 'app-001',
    storeName: 'Goblin Games',
    city: 'Praha',
    country: 'CZ',
    address: 'Vinohradská 42, Praha 3',
    contactName: 'Jan Dvořák',
    contactEmail: 'jan@goblingames.cz',
    website: 'https://goblingames.cz',
    wpn: true,
    status: 'pending',
    submittedAt: '2026-06-14T10:22:00Z',
  },
  {
    id: 'app-002',
    storeName: 'The Mana Den',
    city: 'Brno',
    country: 'CZ',
    address: 'Náměstí Svobody 3, Brno',
    contactName: 'Lucie Nováková',
    contactEmail: 'lucie@manaden.cz',
    wpn: false,
    status: 'pending',
    submittedAt: '2026-06-15T14:05:00Z',
  },
  {
    id: 'app-003',
    storeName: 'Tabletop Arena',
    city: 'Wien',
    country: 'AT',
    address: 'Mariahilfer Str. 77, 1060 Wien',
    contactName: 'Stefan Gruber',
    contactEmail: 'stefan@tabletop-arena.at',
    website: 'https://tabletop-arena.at',
    wpn: true,
    status: 'approved',
    submittedAt: '2026-06-01T09:00:00Z',
    reviewedAt: '2026-06-03T11:30:00Z',
    reviewedBy: 'usr-003',
  },
]
